### PR TITLE
Added amenity=table to StreetFurnitureModule.java

### PR DESCRIPTION
**Pull request by cjhox**
screenshot 2016-11-11 19 54 23

added STEEL to surfaceMaterialMap, because a lot of the StreetFurnitureModules do have a steel surface.
added parseInt to WorldModuleParseUtil.java to get Integers from Tags
added parseLength to WorldModuleParseUtil.java

### CODE REVIEW

**Comment by tordanik** [comment]
Looks good on first glance. Will test it a bit before merging, though. Is it ok if I leave out most of the whitespace changes?

**Comment by cjhox** [comment]
Sorry for the whitespace changes, that was an unnessesery change.
Just ignore them.

I hope its not overdesigned with all this relations to other values. Just
replace the calculations with constances if you want to.

Am 12.11.2016 23:18 schrieb "Tobias Knerr" <notifications@github.com>:

**Comment by sfkeller** [comment]
Note that "amenity=picnic_table" was also added. It's rendered with the same code.

**Comment by tordanik** [comment]
Merged, thanks for your contribution!

**Pull request merged**
