### PR TITLE
Bug fixes, convert to maven and support for more tags

### PR DESCRIPTION
**Pull request by pinglis**
I've made lots of small changes to OSM2World which i thought i would share.  Here is a large'ish pull request which I can split into multiple changes if you prefer. 

Here are the changes the pull request contains:
- Fix for bridges over waterways
- Updated the jts library to 1.13
- #75 Added support for natural/scrub
- #74 Added support for landuse/recreation_ground, leisure/playground, leisure/park, leisure/garden
- Stripped path from materials when writing to obj file (for compatibility with blender)
- Updated the default values of a building 
- Changed normal lane width to 2
- Removed default windows from multistorey carparks
- Make sure buildings have some height
- Prevent writing NaN to obj file
- Set ground state to below for railway tunnels
- Don't write underground objects to obj files if renderUnground option is disabled
- By default, don't give glass buildings windows
- Split road textures to allow different types of roads to have different materials. 
- Use chain link fence module for all metal type fences
- Add columns to barrier modules (can be done better)
- Added some missing breaks to for loops 
- Converted project to maven
- Changed the default width of platforms 
- #106 Stop using RoadJunction if number of connected roads is more than 4 (can be done better)
- Added support for more barrier types
- Fix for flat roofs rendering issues when imported into jme3
- Modification to streetlamp to give it a light at top
- Moved to jogl 2.1
- Changed the default theme to look a better (IMO).  The theme is influenced by http://demo.f4map.com/
- Fix for transparency in obj files (when imported into jme3)
- Set default lanes for roundabouts to 2 (probably not the right thing to do but it always looks better IMO).
- Make obj material file match blenders format (it makes find bugs easier)

### CODE REVIEW

**Comment by tordanik** [comment]
Wow, that's a lot of good stuff. It's going to take a while to review it all, though. I'm coming back to you when I have questions.

**Comment by tordanik** [comment]
Hi again, after reviewing your pull request I've come to the conclusion that I would like to merge the following commits:
* 6507d79
* 8e78832
* 76488ce
* a6a8a15
* 38301b6
* b5000ed
* b71b0ed
* 00c51d6
* 03ec363
* 340052c
* ef49804
* c1e582b

Now the question is how to proceed. The simplest would probably be for me to cherry-pick the commits above. But if you prefer doing it differently, please let me know. In some cases I would also like to only use parts of a commit. In these cases I would do a new commit that names you as the author, assuming you are ok with that?

Ok, so about the other commits:

The switch to Maven and the related changes are something I will probably be doing at some point, but I feel it's a big enough step that I would like to do it on its own after due preparation, not mixed with other improvements.

Regarding 1489406, I agree that your default values are more likely to produce accurate results, and therefore make sense for certain applications. However, I'm trying to encourage mappers to actually add the tags instead of relying on defaults, and to that end I prefer the current defaults. It would likely be best if the priorities ("make the best of the data as it is right now" or "try to encourage improvements to the data")
could be configured. Until then, I would rather stick with the status quo.

As for d5d7a09: I'm intentionally low-balling road widths because errors in the (inherently flawed) junction calculation algorithm, as well as overlaps between road segments and other ugliness are more likely with wider roads. This is again a case where your defaults are closer to the real world (and I encourage you to keep them in your fork), but I would prefer to stick with the status quo.

If you are interested in my reasons for not merging the remaining commits, let me know!

**Comment by pinglis** [comment]
Hi Tobias,

I'm perfectly happy for you to proceed as you suggest.  I'm just glad my
some of my commits are useful.

paul

**Comment by tordanik** [comment]
I've now performed the operations I outlined above, and partially merged your changes into the master branch. Thanks again for the large number of improvements and bug fixes you have contributed! :)

**Pull request closed without merging**
